MyEcommerceAdmin/Models/Supplier.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MyEcommerceAdmin.Models
{
    public partial class Supplier
    {
        public Supplier()
        {
            this.Products = new HashSet<Product>();
        }
        [Key]
        public int SupplierID { get; set; }
        [Required, Display(Name = "Company Name")]
        public string CompanyName { get; set; }
        [Required, Display(Name = "Contact Name")]
        public string ContactName { get; set; }
        [Required, Display(Name = "Contact Title")]
        public string ContactTitle { get; set; }
        [Required]
        public string Address { get; set; }
        [Required]
        public string Phone { get; set; }
        [Required]
        public string Email { get; set; }
        [Required]
        public string City { get; set; }
        [Required]
        public string Country { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}

MyEcommerceAdmin/Controllers/SupplierController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyEcommerceAdmin.Models;

namespace MyEcommerceAdmin.Controllers
{
    public class SupplierController : Controller
    {
        MyEcommerceDbContext db = new MyEcommerceDbContext();
        // GET: Supplier
        public ActionResult Index()
        {
            return View(db.Suppliers.ToList());
        }

        // CREATE: Supplier

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Supplier suplr)
        {
            if (ModelState.IsValid)
            {
                db.Suppliers.Add(suplr);
                db.SaveChanges();
                return PartialView("_Success");
            }
            return PartialView("_Error");
        }


        // EDIT: Supplier

        public ActionResult Edit(int id)
        {
            Supplier suplr = db.Suppliers.Single(x => x.SupplierID == id);
            if (suplr == null)
            {
                return HttpNotFound();
            }
            return View(suplr);
        }

        [HttpPost]
        public ActionResult Edit(Supplier suplr)
        {
            if (ModelState.IsValid)
            {
                db.Entry(suplr).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(suplr);
        }


        // DETAILS: Supplier

        public ActionResult Details(int id)
        {
            Supplier suplr = db.Suppliers.Find(id);
            if (suplr == null)
            {
                return HttpNotFound();
            }
            return View(suplr);
        }

        // DELETE: Supplier

        public ActionResult Delete(int id)
        {
            Supplier suplr = db.Suppliers.Find(id);
            if (suplr == null)
            {
                return HttpNotFound();
            }
            return View(suplr);
        }

        //Post Delete Confirmed

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Supplier suplr = db.Suppliers.Find(id);
            db.Suppliers.Remove(suplr);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

MyEcommerceAdmin/Views/Supplier/Create.cshtml
@model MyEcommerceAdmin.Models.Supplier
@{
    ViewBag.Title = "Add New Supplier";
}

<div class="row">
    <div class="col">
        <h2 class="text-info">Add New Supplier</h2>
        <hr />
        <div class="col-md-12">
            @using (Ajax.BeginForm(new AjaxOptions { HttpMethod = "POST", InsertionMode = InsertionMode.Replace, UpdateTargetId = "msg", OnComplete = "clearAll" }))
            {
                @Html.AntiForgeryToken()
                <div class="row mb-2">
                    <div id="msg">

                    </div>
                </div>
                <div class="row g-3">
                    <div class="col-md-12">
                        @Html.LabelFor(x => x.CompanyName, new { @class = "form-label fs-4" })
                        @Html.TextBoxFor(x => x.CompanyName, new { @class = "form-control fs-4" })
                        @Html.ValidationMessageFor(x => x.CompanyName, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-md-6">
                        @Html.LabelFor(x => x.ContactName, new { @class = "form-label fs-4" })
                        @Html.TextBoxFor(x => x.ContactName, new { @class = "form-control fs-4" })
                        @Html.ValidationMessageFor(x => x.ContactName, "", new { @class = "text-danger" })
                    </div>

                    <div class="col-md-6">
                        @Html.LabelFor(x => x.ContactTitle, new { @class = "form-label fs-4" })
                        @Html.TextBoxFor(x => x.ContactTitle, new { @class = "form-control fs-4" })
                        @Html.ValidationMessageFor(x => x.ContactTitle, "", new { @class = "text-danger" })
                    </div>

                    <div class="col-md-6">
                        @Html.LabelFor(x => x.Email, new { @class = "form-label fs-4" })
                        @Html.TextBoxFor(x => x.Email, new { @class = "form-control fs-4", Type = "email" })
                        @Html.ValidationMessageFor(x => x.Email, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-md-6">
                        @Html.LabelFor(x => x.Phone, new { @class = "form-label fs-4" })
                        @Html.TextBoxFor(x => x.Phone, new { @class = "form-control fs-4" })
                        @Html.ValidationMessageFor(x => x.Phone, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-md-6">
                        @Html.LabelFor(x => x.Country, new { @class = "form-label fs-4" })
                        @Html.TextBoxFor(x => x.Country, new { @class = "form-control fs-4" })
                        @Html.ValidationMessageFor(x => x.Country, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-md-6">
                        @Html.LabelFor(x => x.City, new { @class = "form-label fs-4" })
                        @Html.TextBoxFor(x => x.City, new { @class = "form-control fs-4" })
                        @Html.ValidationMessageFor(x => x.City, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-md-6">
                        @Html.LabelFor(x => x.Address, new { @class = "form-label fs-4" })
                        @Html.TextAreaFor(x => x.Address, new { @class = "form-control fs-4" })
                        @Html.ValidationMessageFor(x => x.Address, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-md-6" style="padding-top:50px;">
                        <button type="submit" class="btn btn-success btn-lg col-12"><i class="fa-regular fa-floppy-disk fs-4"></i> Save</button>
                    </div>
                </div>
            }

            <div class="col-md-12 d-flex justify-content-lg-start mt-3">
                <a href="@Url.Action("Index", "Supplier")" class="btn btn-danger btn-sm fs-4"><i class="fa-regular fa-hand-back-point-left"></i> Back to the list</a>
            </div>
        </div>
    </div>
</div>
@section scripts{
    <script src="~/Content/JS/jquery-3.6.0.js"></script>
    <script src="~/Content/JS/jquery.validate.js"></script>
    <script src="~/Content/JS/jquery.validate.unobtrusive.js"></script>
    <script src="~/Content/JS/jquery.unobtrusive-ajax.js"></script>
    <script>
        function clearAll() {
            $("#form0").trigger("reset");
        }
    </script>

}

MyEcommerceAdmin/Views/Supplier/Delete.cshtml
@model MyEcommerceAdmin.Models.Supplier
@{
    ViewBag.Title = "Supplier Details";
}
<Div class="row">
    <div class="col">
        <div class="col-md-12">
            @using (Html.BeginForm("Delete", "Supplier", FormMethod.Post))
            {
                @Html.HiddenFor(x => x.SupplierID)
                @Html.AntiForgeryToken()
                <section class="section about-section gray-bg" id="about">
                    <div class="container">
                        <div class="row align-items-center flex-row-reverse">
                            <div class="col-lg-7">
                                <div class="about-text go-to">
                                    <h2 class="dark-color text-danger">Conform to Delete Supplier </h2>
                                    <hr />
                                    <h3 class="theme-color lead fs-2">@Html.DisplayFor(x => x.CompanyName)</h3>
                                    <div class="row about-list">
                                        <div class="col-md-6">
                                            <div class="media">
                                                <label class="fs-4">Contact Name</label>
                                                <p>@Html.DisplayFor(x => x.CompanyName)</p>
                                            </div>
                                            <div class="media">
                                                <label class="fs-4">Contact Title</label>
                                                <p>@Html.DisplayFor(x => x.ContactTitle)</p>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="media">
                                                <label class="fs-4">E-mail</label>
                                                <p>@Html.DisplayFor(x => x.Email)</p>
                                            </div>
                                            <div class="media">
                                                <label class="fs-4">Phone</label>
                                                <p>@Html.DisplayFor(x => x.Phone)</p>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="media">
                                                <label class="fs-4">Country</label>
                                                <p>@Html.DisplayFor(x => x.Country)</p>
                                            </div>
                                            <div class="media">
                                                <label class="fs-4">City</label>
                                                <p>@Html.DisplayFor(x => x.City)</p>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="media">
                                                <label class="fs-4">Address</label>
                                                <p>@Html.DisplayFor(x => x.Address)</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-5">
                                <div class="about-avatar">
                                    <img src="~/Content/img/Supplier-Static-Img.jpg" width="350" height="350" />
                                </div>
                            </div>
                        </div>
                        <div class="counter mt-4">
                            <div class="row">
                                <div class="col-6 col-lg-3">
                                    <a href="@Url.Action("Index", "Supplier")" class="btn btn-info btn-sm fs-4"><i class="fa-regular fa-hand-back-point-left"></i> Back to the list</a>
                                </div>
                                <div class="col-6 col-lg-3">
                                    <button type="submit" class="btn btn-danger fs-4"><i class="fa-solid fa-trash fs-4"></i>&nbsp;Conform Delete</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            }
        </div>
    </div>
</Div>

MyEcommerceAdmin/Views/Supplier/Details.cshtml
@model MyEcommerceAdmin.Models.Supplier
@{
    ViewBag.Title = "Supplier Details";
}

<section class="section about-section gray-bg" id="about">
    <div class="container">
        <div class="row align-items-center flex-row-reverse">
            <div class="col-lg-7">
                <div class="about-text go-to">
                    <h2 class="dark-color">Individual Supplier Details</h2>
                    <hr />
                    <h3 class="theme-color lead fs-2">@Html.DisplayFor(x=>x.CompanyName)</h3>
                    <div class="row about-list">
                        <div class="col-md-6">
                            <div class="media">
                                <label class="fs-4">Contact Name</label>
                                <p>@Html.DisplayFor(x => x.ContactName)</p>
                            </div>
                            <div class="media">
                                <label class="fs-4">Contact Title</label>
                                <p>@Html.DisplayFor(x => x.ContactTitle)</p>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="media">
                                <label class="fs-4">E-mail</label>
                                <p>@Html.DisplayFor(x => x.Email)</p>
                            </div>
                            <div class="media">
                                <label class="fs-4">Phone</label>
                                <p>@Html.DisplayFor(x => x.Phone)</p>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="media">
                                <label class="fs-4">Country</label>
                                <p>@Html.DisplayFor(x => x.Country)</p>
                            </div>
                            <div class="media">
                                <label class="fs-4">City</label>
                                <p>@Html.DisplayFor(x => x.City)</p>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="media">
                                <label class="fs-4">Address</label>
                                <p>@Html.DisplayFor(x => x.Address)</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-5">
                <div class="about-avatar">
                    <img src="~/Content/img/Supplier-Static-Img.jpg" width="350" height="350"/>
                </div>
            </div>
        </div>
        <div class="counter mt-4">
            <div class="row">
                <div class="col-6 col-lg-3">
                    <a href="@Url.Action("Index", "Supplier")" class="btn btn-danger btn-sm fs-4"><i class="fa-regular fa-hand-back-point-left"></i> Back to the list</a>
                </div>
            </div>
        </div>
    </div>
</section>

MyEcommerceAdmin/Views/Supplier/Edit.cshtml
@model MyEcommerceAdmin.Models.Supplier
@{
    ViewBag.Title = "Edit Employee Profile";
}

<div class="row">
    <div class="col">
        <div class="row g-3">
            <div class="col-md-4">
                <h2 class="text-info">@Model.CompanyName</h2>
            </div>
        </div>
        <hr />
        <div class="col-md-12">
            @using (Html.BeginForm("Edit", "Supplier", FormMethod.Post))
            {
                @Html.HiddenFor(x => x.SupplierID)

                <div class="row g-3">
                    <div class="col-md-12">
                        @Html.LabelFor(x => x.CompanyName, new { @class = "form-label fs-4" })
                        @Html.TextBoxFor(x => x.CompanyName, new { @class = "form-control fs-4" })
                        @Html.ValidationMessageFor(x => x.CompanyName, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-md-6">
                        @Html.LabelFor(x => x.ContactName, new { @class = "form-label fs-4" })
                        @Html.TextBoxFor(x => x.ContactName, new { @class = "form-control fs-4" })
                        @Html.ValidationMessageFor(x => x.ContactName, "", new { @class = "text-danger" })
                    </div>

                    <div class="col-md-6">
                        @Html.LabelFor(x => x.ContactTitle, new { @class = "form-label fs-4" })
                        @Html.TextBoxFor(x => x.ContactTitle, new { @class = "form-control fs-4" })
                        @Html.ValidationMessageFor(x => x.ContactTitle, "", new { @class = "text-danger" })
                    </div>

                    <div class="col-md-6">
                        @Html.LabelFor(x => x.Email, new { @class = "form-label fs-4" })
                        @Html.TextBoxFor(x => x.Email, new { @class = "form-control fs-4", Type = "email" })
                        @Html.ValidationMessageFor(x => x.Email, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-md-6">
                        @Html.LabelFor(x => x.Phone, new { @class = "form-label fs-4" })
                        @Html.TextBoxFor(x => x.Phone, new { @class = "form-control fs-4" })
                        @Html.ValidationMessageFor(x => x.Phone, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-md-6">
                        @Html.LabelFor(x => x.Country, new { @class = "form-label fs-4" })
                        @Html.TextBoxFor(x => x.Country, new { @class = "form-control fs-4" })
                        @Html.ValidationMessageFor(x => x.Country, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-md-6">
                        @Html.LabelFor(x => x.City, new { @class = "form-label fs-4" })
                        @Html.TextBoxFor(x => x.City, new { @class = "form-control fs-4" })
                        @Html.ValidationMessageFor(x => x.City, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-md-6">
                        @Html.LabelFor(x => x.Address, new { @class = "form-label fs-4" })
                        @Html.TextAreaFor(x => x.Address, new { @class = "form-control fs-4" })
                        @Html.ValidationMessageFor(x => x.Address, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-md-6" style="padding-top:50px;">
                        <button type="submit" class="btn btn-success btn-lg col-12"><i class="fa-solid fa-up fs-4"></i> Update</button>
                    </div>
                </div>
            }

            <div class="col-md-12 d-flex justify-content-lg-start mt-3">
                <a href="@Url.Action("Index", "Supplier")" class="btn btn-danger btn-sm fs-4"><i class="fa-regular fa-hand-back-point-left"></i> Back to the list</a>
            </div>
        </div>
    </div>
</div>

MyEcommerceAdmin/Views/Supplier/Index.cshtml
@model IEnumerable<MyEcommerceAdmin.Models.Supplier>
@{
    ViewBag.Title = "Supplier Information";
}

<div class="row">
    
    <div class="col">
        <h2 class="text-info">Supplier List</h2>
        <hr />
        <div class="d-flex justify-content-end mb-2">
            <a href="@Url.Action("Create", "Supplier")" class="btn btn btn-outline-primary"><i class="fa-regular fa-square-plus fs-1"></i></a>
        </div>
        <div class="table-responsive">
            <table class="table table-condensed table-hover table-bordered table-striped table">
                <thead>
                    <tr>
                        <th>@Html.DisplayNameFor(s=> s.CompanyName)</th>
                        <th>@Html.DisplayNameFor(s => s.ContactName)</th>
                        <th>@Html.DisplayNameFor(s => s.ContactTitle)</th>
                        <th>@Html.DisplayNameFor(s => s.Phone)</th>
                        <th>@Html.DisplayNameFor(s => s.Email)</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var sup in Model)
                    {
                        <tr>
                            <td>@Html.DisplayFor(s => sup.CompanyName)</td>
                            <td>@Html.DisplayFor(s => sup.ContactName)</td>
                            <td>@Html.DisplayFor(s => sup.ContactTitle)</td>
                            <td>@Html.DisplayFor(s => sup.Phone)</td>
                            <td>@Html.DisplayFor(s => sup.Email)</td>
                            <td>
                                <a href="@Url.Action("Edit", "Supplier", new {id = sup.SupplierID })" class="btn btn-outline-warning btn-sm"><i class="fa-solid fa-pen-to-square fs-4"></i></a>
                                <a href="@Url.Action("Details", "Supplier", new {id = sup.SupplierID })" class="btn btn-outline-info btn-sm"><i class="fa-regular fa-circle-info fs-4"></i></a>
                                <a href="@Url.Action("Delete", "Supplier", new {id = sup.SupplierID })" class="btn btn-outline-danger btn-sm"><i class="fa-regular fa-trash-arrow-up fs-4"></i></a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>